---

- hosts: all
  become: yes
  
  pre_tasks:
    
    - include_vars: "{{ item }}"
      with_fileglob: "{{ config_files }}"
    
  roles:
    
    - { role: php-imagick }
    - { role: drush_aliases }